version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=fastapidb
      - POSTGRES_USER=fastapiuser
      - POSTGRES_PASSWORD=fastapipassword
    volumes:
      - ./app:/app

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: fastapidb
      POSTGRES_USER: fastapiuser
      POSTGRES_PASSWORD: fastapipassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: